// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF6exeT2hpQTIutU5-2QlpQkA6X_u0SK8',
    appId: '1:939713848172:web:f5361aaf3f0c3236ae4949',
    messagingSenderId: '939713848172',
    projectId: 'tasontime',
    authDomain: 'tasontime.firebaseapp.com',
    storageBucket: 'tasontime.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm5DT5QI-yHKm7WD9D5xAwo_fND8nBFQE',
    appId: '1:939713848172:android:7a4419e1fa32b82dae4949',
    messagingSenderId: '939713848172',
    projectId: 'tasontime',
    storageBucket: 'tasontime.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzLNF5vW74kRO_gA8UyR3shIt0E9CiM1Q',
    appId: '1:939713848172:ios:f917b7d919caaad5ae4949',
    messagingSenderId: '939713848172',
    projectId: 'tasontime',
    storageBucket: 'tasontime.appspot.com',
    iosBundleId: 'com.example.tasontime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBzLNF5vW74kRO_gA8UyR3shIt0E9CiM1Q',
    appId: '1:939713848172:ios:be07cd94e6f0e046ae4949',
    messagingSenderId: '939713848172',
    projectId: 'tasontime',
    storageBucket: 'tasontime.appspot.com',
    iosBundleId: 'com.example.tasontime.RunnerTests',
  );
}
